theme: jekyll-theme-minimal
title: 'Artificial Sommelier'
description: 'This is a project for the course Cognitive Computational Modeling of Language and Web Interaction from the Radboud University (Nijmegen). The goal of this project was to reproduce the work by Hendrickx et al. (2016) but give it our own twist. We were mostly interested in trying to predict the score for a specific wine given an experts review.'
logo: 'images/wine-logo.jpg'
show_downloads: 'false'


